Fix an issue when content_to_trans is empty
The text returned from google speech_to_text can be empty. In this case, an error is thrown during translation : 
```
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```